### ISSUE TITLE
Question about Collecting and pre-processing data

### ISSUE THREAD

**Issue by K0909github** [mazpie/genrl#17]
Thanks for this sharing this work. I am very interested for it.

I have a question for it.

[data/stickman_example/1000-20240504T040956-d7ee0ea24b3e4863b1ef5e5bf1849924-501.npz] have ['observation', 'is_first', 'is_last', 'is_terminal', 'action', 'reward', 'discount', 'clip_video', 'clip_img'].

So, i think that my collecting data have['observation', 'is_first', 'is_last', 'is_terminal', 'action', 'reward', 'discount', 'clip_video', 'clip_img'] too.

But,my collecting data(Result of running collect_data.py agent=dreamer task=stickman_walk) have['observation', 'is_first', 'is_last', 'is_terminal', 'action', 'reward', 'discount'].

So,When I run genrl/process_dataset.py, I get a [KeyError: 'clip_video'] error.
Does this work right?

Thanks,
K0909

**Comment by mazpie** [comment]
Hi @K0909github,

There is probably a bug at line 101: https://github.com/mazpie/genrl/blob/e8bd1035a2f9389305947a3034ac9694c11c77fd/process_dataset.py#L101

I think it should be solved by simply adding a check for the key before that line.
The code should be:

```
                    # if key existing, validate before continuing
                    if self.key_to_add in episode:
                            if type(episode[self.key_to_add]) == np.ndarray and episode[self.key_to_add].size > 1 and episode[self.key_to_add].shape[0] == episode[self.key_to_process].shape[0]:
                                continue
                            else:
                                del episode[self.key_to_add]
```

Let me know if it works!

**Comment by K0909github** [comment]
Very thanks for the reply,@mazpie.
But,I failed again.
Specifically,I executed this.
`def process(self):
        filenames = sorted(self.dataset_path.glob('**/*.npz'))
        print(f"Found {len(filenames)} files")
        episodes_to_process = {}

        for idx, fname in tqdm(enumerate(filenames)):
            lockname = str(fname.absolute()) + ".lck"
            try:
                with Locker(lockname):
                    episode = load_episode(fname)

                    # if key existing, validate before continuing
                    if self.key_to_add in episode:
                            if type(episode[self.key_to_add]) == np.ndarray and episode[self.key_to_add].size > 1 and episode[self.key_to_add].shape[0] == episode[self.key_to_process].shape[0]:
                                continue
                            else:
                                del episode[self.key_to_add]

                    # validate before continuing
                    if type(episode[self.key_to_add]) == np.ndarray and episode[self.key_to_add].size > 1 and episode[self.key_to_add].shape[0] == episode[self.key_to_process].shape[0]:
                        continue
                    else:
                        del episode[self.key_to_add]

                    add_data = self.train_env.process_episode(episode[self.key_to_process]) # .cpu().numpy()
                    if idx == 0:
                        print(add_data.shape)
                    episode[self.key_to_add] = add_data

                    # save episode
                    with io.BytesIO() as f1:
                        np.savez_compressed(f1, **episode)
                        f1.seek(0)
                        with fname.open('wb') as f2:
                            f2.write(f1.read())
            except BlockingIOError:
                print(f"File busy: {str(fname)}")
                continue`


Consequentry,this error occured.


Error executing job with overrides: ['dataset_dir=/home/ubuntu/exp_local/2025.03.18/151709_dreamer/buffer']
Traceback (most recent call last):
  File "/home/ubuntu/genrl/process_dataset.py", line 148, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/ubuntu/genrl/process_dataset.py", line 145, in main
    start_processing(cfg, None, None)
  File "/home/ubuntu/genrl/process_dataset.py", line 141, in start_processing
    workspace.process()
  File "/home/ubuntu/genrl/process_dataset.py", line 109, in process
    if type(episode[self.key_to_add]) == np.ndarray and episode[self.key_to_add].size > 1 and episode[self.key_to_add].shape[0] == episode[self.key_to_process].shape[0]:
KeyError: 'clip_video'



Additionary,my results are below.

import numpy as np
data = np.load("/home/ubuntu/genrl/data/stickman_example/1000-20240504T040956-d7ee0ea24b3e4863b1ef5e5bf1849924-501.npz")
print(data.files)

this resuit is below.
['observation', 'is_first', 'is_last', 'is_terminal', 'action', 'reward', 'discount', 'clip_video', 'clip_img']

but

import numpy as np
data = np.load("/home/ubuntu/exp_local/2025.03.18/151709_dreamer/buffer/10-20250318T153901-43adf44cbb034dc39014c7eddf85b49d-501.npz")
print(data.files)

this result is below.
['observation', 'is_first', 'is_last', 'is_terminal', 'action', 'reward', 'discount'].

**Comment by mazpie** [comment]
Hi @K0909github,

I see you have the same validation part twice in the code.

Since you added the code I suggested, you should remove the following:

```
                # validate before continuing
                if type(episode[self.key_to_add]) == np.ndarray and episode[self.key_to_add].size > 1 and episode[self.key_to_add].shape[0] == episode[self.key_to_process].shape[0]:
                    continue
                else:
                    del episode[self.key_to_add]
```

and hopefully it will work!

**Comment by K0909github** [comment]
I can't thank you enough,@mazpie.
Very much improved, but still a problem.

I was able to run the prosess.py without error, but it did not contain clip_img.
Specifically,i executed this.

!HYDRA_FULL_ERROR=1 python3 genrl/process_dataset.py dataset_dir=/home/ubuntu/exp_local/2025.03.18/053731_dreamer/buffer 

thereafter,I executed this.

import numpy as np
data = np.load("/home/ubuntu/exp_local/2025.03.18/053731_dreamer/buffer/1-20250318T053737-0840d88d6a9f4c99be6093ba0361c008-501.npz")
print(data.files)

This is the result.
['observation', 'is_first', 'is_last', 'is_terminal', 'action', 'reward', 'discount', 'clip_video'].

**Comment by mazpie** [comment]
Right now, the repo only contains the code for obtaining the 'clip_video' embeddings.

If you need the 'clip_img', I can share that part of the code as well. Though, it will take some time (weeks probably, as I am a bit busy these days) as I need to clean it and make it compatible with the public version of the code.
